name: mfw
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 弱提示
  fluttertoast: ^2.0.8
  # 下拉刷新上拉加载
  flutter_refresh: ^0.0.2
  # 图片选择
  # 苹果配置：https://pub.flutter-io.cn/packages/image_picker#-readme-tab-
  image_picker: ^0.4.10
  # 视频选择和播放
  # 配置：https://pub.flutter-io.cn/packages/video_player#-readme-tab-
  video_player: ^0.6.5
  # 图片裁剪
  # 安卓配置：https://pub.flutter-io.cn/packages/image_cropper#-readme-tab-
#  image_cropper: ^0.0.6

  # 分享modal
  share: ^0.5.3
  # 富文本编译（运行没效果）
  # flutter_markdown: ^0.2.0
  # 二维码和条形码扫描
  barcode_scan: ^0.0.7
  # 缓存网络图片
  cached_network_image: ^0.4.2
  # 路由管理（暂未使用）
  fluro: "^1.3.5"
  # 左右滑动删除
  flutter_slidable: ^0.4.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  # tabbar
  - assets/images/ic_tab_homepage_normal.png
  - assets/images/ic_tab_homepage_selected.png
  - assets/images/ic_tab_destination_normal.png
  - assets/images/ic_tab_destination_selected.png
  - assets/images/ic_tab_expand_normal.png
  - assets/images/ic_tab_expand_selected.png
  - assets/images/ic_tab_hotel_normal.png
  - assets/images/ic_tab_hotel_selected.png
  - assets/images/ic_tab_mine_normal.png
  - assets/images/ic_tab_mine_selected.png

  # mine
  - assets/images/icon_setup.png
  - assets/images/icon_scavenging.png
  - assets/images/icon_message.png


  - assets/images/ic_default._head.png
  - assets/images/ic_my_set.png
  - assets/images/ic_arrow_right.png
  - assets/images/ic_my_faceImage.png
  - assets/images/ic_mm.png
  - assets/images/refresh.png
  - assets/images/v.jpg
  - assets/images/dot.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
